// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEEiHRe1nidZO59PJGLl703D4c04oeNrI',
    appId: '1:387641466022:web:ffb40752921856adfe6867',
    messagingSenderId: '387641466022',
    projectId: 'swikeynotes-flutter-project',
    authDomain: 'swikeynotes-flutter-project.firebaseapp.com',
    storageBucket: 'swikeynotes-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEWBlzl2jk4u4QvycaxJeGlHC0M9cKqZQ',
    appId: '1:387641466022:android:c29032c4b26b79fafe6867',
    messagingSenderId: '387641466022',
    projectId: 'swikeynotes-flutter-project',
    storageBucket: 'swikeynotes-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxRMe9su-Ao9SeCuhgRMWVS9OncfS5tWg',
    appId: '1:387641466022:ios:c06f0d7ca80db3cdfe6867',
    messagingSenderId: '387641466022',
    projectId: 'swikeynotes-flutter-project',
    storageBucket: 'swikeynotes-flutter-project.appspot.com',
    iosClientId: '387641466022-98qqkrr4cbqa3oktktjvoijs1va57bhe.apps.googleusercontent.com',
    iosBundleId: 'com.swikey.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxRMe9su-Ao9SeCuhgRMWVS9OncfS5tWg',
    appId: '1:387641466022:ios:c06f0d7ca80db3cdfe6867',
    messagingSenderId: '387641466022',
    projectId: 'swikeynotes-flutter-project',
    storageBucket: 'swikeynotes-flutter-project.appspot.com',
    iosClientId: '387641466022-98qqkrr4cbqa3oktktjvoijs1va57bhe.apps.googleusercontent.com',
    iosBundleId: 'com.swikey.mynotes',
  );
}
